import App from './App'

export default [
  {
    path:'/',
    component:App.components.Index,
    name:'index'
  },
  {
    path:'/details/:id',
    component:App.components.vDetails,
    name:'details'
  },
  {
    path:'/themes/:id',
    component:App.components.Themes,
    name:'themes'
  },
  {
    path:'/comments/:id',
    component:App.components.Comments,
    name:'comments'
  },
	{
		path:'/header',
		component:App.components.vHeader,
		name:'header'
	},
	{
		path:'/hello',
		component:App.components.Hello,
		name:'hello'
	},
	{
		path:'/slide',
		component:App.components.Slide,
		name:'slide'
	},
  {
    path:'/side',
    component:App.components.Side,
    name:'side'
  }
]
